---
- name: backup_datasets
  hosts: fs_prod_1
  become: true

  vars:
    log: "/mnt/md2/other/logs/{{ ansible_play_name }}_$(date +'%Y%m%d').log"

  tasks:
    - name: md1 to md0
      shell: "rsync -avh --exclude 'lost+found' /mnt/md1/ /mnt/md0 --log-file={{ log }}"
    - name: md1 to sd1
      shell: "rsync -avh --exclude 'lost+found' /mnt/md1/ /mnt/sd1 --log-file={{ log }}"
    - name: md2 to md0
      shell: "rsync -avh --exclude 'lost+found' --exclude 'temp' --exclude 'proxmox/containers' /mnt/md2/ /mnt/md0 --log-file={{ log }}"
    - name: md2 to sd2
      shell: "rsync -avh --exclude 'lost+found' --exclude 'temp' --exclude 'proxmox/containers' /mnt/md2/ /mnt/sd2 --log-file={{ log }}"