---
- name: delete_outdated_proxmox
  hosts: fs_prod_1
  become: true

  vars:
    base_cmd: "rsync -v --recursive --delete --ignore-existing --existing --prune-empty-dirs"
    log: "/mnt/md2/other/logs/{{ ansible_play_name }}_$(date +'%Y%m%d').log"
    src: /mnt/md2/proxmox/
    dest:
      - /mnt/md0/proxmox/
      - /mnt/sd2/proxmox/

  tasks:
    - name: "delete from {{ item }}"
      shell: "{{ base_cmd }} {{ src }} {{ item }} --log-file={{ log }}"
      loop: "{{ dest }}"