---
- name: Dataset Syncs
  hosts: fs_prod_1
  become: yes
  become_user: root
  become_method: su
  become_exe: sudo su -

  tasks:
    - name: Copy md1 to md0
      ansible.posix.synchronize:
        src: /mnt/md2/temp
        dest: /mnt/sd2/temp
      delegate_to: localhost