---
- name: Dataset Syncs
  hosts: fs_prod_1
  become: true

  tasks:
    - name: Install additional packages
      apt:
        name:
          - sudo
          - acl
        state: present
    - name: Copy md1 to md0
      ansible.posix.synchronize:
        src: /mnt/md2/temp
        dest: /mnt/sd2/temp
      delegate_to: localhost